# Generated by Django 5.2.16 on 2026-07-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('youtube_id', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
