# Generated by Django 5.2.16 on 2026-07-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_forumcategory_event_created_at_event_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HymnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('hymn_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('composer', models.CharField(blank=True, max_length=255)),
                ('lyrics', models.TextField()),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('tune_name', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hymn_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hymns', to='api.hymnbook')),
            ],
            options={
                'ordering': ['hymn_book', 'number'],
                'unique_together': {('hymn_book', 'number')},
            },
        ),
    ]
