# Generated by Django 5.2.16 on 2026-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hymnbook_hymn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabbathProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(unique=True)),
                ('theme', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_date'],
            },
        ),
    ]
